# Generated by Django 5.0.4 on 2024-04-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='face_encoding_array2',
            field=models.BinaryField(null=True),
        ),
    ]
